### ISSUE TITLE
Error in 2020-12-05 Benchmark

### ISSUE THREAD

**Issue by quasiben** [quasiben/dask-scheduler-performance#43]
Benchmark scheduler for 2020 12 05 (today) failed with the following output:

```bash
+ srun -N1 python nightly-run.py
distributed.core - ERROR - Exception while handling op performance_report
Traceback (most recent call last):
  File "/gpfs/fs1/bzaitlen/miniconda3/envs/20201205-nightly-0.17/lib/python3.8/site-packages/distributed/core.py", line 517, in handle_comm
    result = await result
  File "distributed/scheduler.py", line 5539, in genexpr
  File "distributed/scheduler.py", line 5539, in genexpr
AttributeError: 'distributed.scheduler.WorkerState' object has no attribute '_nthreads'
```

Also seeing the following output during the `run-shuffle` benchmark 

```
+ export DASK_OPTIMIZATION__FUSE__ACTIVE=False
+ DASK_OPTIMIZATION__FUSE__ACTIVE=False
+ srun -N1 bash run-shuffle.sh
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Client Client-2c89b8d7-36ec-11eb-b80a-a81e84cca753 requests to cancel 1440 keys
distributed.scheduler - INFO - Scheduler cancels key ('shuffle-2-0be9007f45f6451d3f65d03c3601d635', 411).  Force=False
distributed.scheduler - INFO - Scheduler cancels key ('shuffle-2-0be9007f45f6451d3f65d03c3601d635', 62).  Force=False
distributed.scheduler - INFO - Scheduler cancels key ('shuffle-2-0be9007f45f6451d3f65d03c3601d635', 1111).  Force=False
```

Lastly, output also has warnings which have previously seen in https://github.com/dask/distributed/issues/4305

```
Exception ignored in: <function Future.__del__ at 0x7fad6c44bee0>
Traceback (most recent call last):
  File "/gpfs/fs1/bzaitlen/miniconda3/envs/20201205-nightly-0.17/lib/python3.8/site-packages/distributed/client.py", line 384, in __del__
  File "/gpfs/fs1/bzaitlen/miniconda3/envs/20201205-nightly-0.17/lib/python3.8/site-packages/distributed/client.py", line 359, in release
  File "/gpfs/fs1/bzaitlen/miniconda3/envs/20201205-nightly-0.17/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 222, in add_callback
AttributeError: 'NoneType' object has no attribute 'get_ident'
```

**Comment by jrbourbeau** [comment]
@jakirkham pushed up some fixes in https://github.com/dask/distributed/pull/4321 which might not have been included in the latest benchmark run. I suspect that will resolve the `'distributed.scheduler.WorkerState' object has no attribute '_nthreads'` error

**Comment by jakirkham** [comment]
Does this help ( https://github.com/dask/distributed/pull/4321 )?

**Comment by quasiben** [comment]
Thanks @jakirkham and @jrbourbeau dask/distributed#4321  resolved the issues. New benchmark issue should be up shortly.  When it arrives,  I'll close this

**Comment by jakirkham** [comment]
Thanks Ben! 😀

Also sorry for duping James 😞 Mobile isn’t as good at showing the page well writing a comment.

**Comment by jakirkham** [comment]
New report is here ( https://github.com/quasiben/dask-scheduler-performance/issues/44 )
